version: "3.8"
services:
  podcast_django:
    build: .
    volumes:
      - .:/podcast
    ports:
      - 8000:8000
    image: podcast_django:runserver
    container_name: podcast_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'django-app-db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/mysql/db:/var/lib/mysql


